pipeline {
    agent any
    environment {
        GIT_URL = 'git@github.com:VinodKumarPasam/Acmeshop-app.git'
        AWS_Region = 'us-east-1'
        ECR_Registry = '818957473542.dkr.ecr.us-east-1.amazonaws.com'
        ECR_Repository = 'acmeshop/product-service'
        IMAGE_TAG = ''
        GIT_BRANCH = 'develop'
    }
    stages 
    {
        stage ("git checkout") {
            steps {
                git branch: "${GIT_BRANCH}", url: "${GIT_URL}",
                credentialsId: 'github-acmeshop-jenkins'


            }
        }
         stage ('set image tag') {
            steps {
                script {
                    env.IMAGE_TAG = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                }
            }
        }

        stage ('build-product-service') {
            steps {
                dir('acmeshop-product-service') {
                    sh '''
                    docker build -t ${ECR_Registry}/${ECR_Repository}:${IMAGE_TAG} .   
                    
                    '''
                }
            }
        }
        stage ('ECR login') {
            steps {
                withCredentials([ $class : 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws configure']) {
                    sh '''
                        aws ecr get-login-password --region ${AWS_Region} | docker login --username AWS --password-stdin ${ECR_Registry}
                    '''
            }
        }
    }
    stage ('Docker image push') {
        steps {
            sh '''
                docker push ${ECR_Registry}/${ECR_Repository}:${IMAGE_TAG}
            '''
        }
    }
    }
post {
    success {
        echo "Docker image pushed successfully to ECR: ${ECR_Registry}/${ECR_Repository}:${IMAGE_TAG}"
    }
    failure {
        echo "Docker image push failed. Please check the logs for details."
    }
}
}